apiVersion: karpenter.sh/v1
kind: NodePool
metadata:
  name: default
spec:
  template:
    spec:
      requirements:
        - key: kubernetes.io/arch
          operator: In
          values: ["amd64"]
        - key: kubernetes.io/os
          operator: In
          values: ["linux"]
        - key: karpenter.sh/capacity-type
          operator: In
          values: ["spot", "on-demand"]
        - key: node.kubernetes.io/instance-type
          operator: In
          values: ["m5.large", "m5.xlarge", "c5.large", "c5.xlarge"]
      nodeClassRef:
        group: karpenter.k8s.aws
        kind: EC2NodeClass
        name: default
  limits:
    cpu: 1000
  disruption:
    consolidationPolicy: WhenEmpty
    consolidateAfter: 30s
---
apiVersion: karpenter.k8s.aws/v1
kind: EC2NodeClass
metadata:
  name: default
spec:
  amiFamily: AL2
  amiSelectorTerms:
    - tags:
        karpenter.sh/discovery: "k8squickstart-cluster"
  subnetSelectorTerms:
    - tags:
        karpenter.sh/discovery: "k8squickstart-cluster"
  securityGroupSelectorTerms:
    - tags:
        karpenter.sh/discovery: "k8squickstart-cluster"
  instanceProfile: "KarpenterNodeInstanceProfile-k8squickstart-cluster"
  userData: |
    #!/bin/bash
    /etc/eks/bootstrap.sh k8squickstart-cluster